# Generated by Django 5.2.4 on 2026-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('pressure_warning', models.FloatField(default=70.0)),
                ('pressure_critical', models.FloatField(default=80.0)),
                ('temperature_warning', models.FloatField(default=130.0)),
                ('temperature_critical', models.FloatField(default=150.0)),
                ('flowrate_min', models.FloatField(default=10.0)),
                ('flowrate_max', models.FloatField(default=200.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Threshold Settings',
            },
        ),
    ]
