# Generated by Django 5.2.4 on 2026-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alertlog_alertsettings_maintenanceschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
